import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-supplier-rebate-accrual-recovery",
  "engine": "recovery",
  "title": "Supplier Rebate Accrual Recovery",
  "shortTitle": "Supplier Rebate Accrual Recovery",
  "tagline": "Calculate earned supplier rebates and recover missing accruals, claims, credits, and cash.",
  "industry": "Procurement Revenue Recovery",
  "buyer": "Manufacturers, distributors, and procurement teams",
  "uiPort": 4702,
  "apiPort": 5702,
  "accent": "#0f766e",
  "currency": "USD",
  "primaryOutcome": "Supplier Rebate Accrual Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect supplier agreements, purchases, eligible products, tiers, growth targets, mix incentives, exclusions, accruals, claims, credits, and payments in one accountable workflow. Calculate earned supplier rebates and recover missing accruals, claims, credits, and cash.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Supplier Rebate Accrual Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("supplier-agreement-library","SRA01","Supplier agreement library","Execute supplier agreement library using supplier agreements, purchases, eligible products, tiers, growth targets, mix incentives, exclusions, accruals, claims, credits, and payments.","Produce a governed supplier agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Rebate Program","text","Supplier / Rebate Program · Standard Case"],["caseReference","Supplier agreement library Reference","text","SRA01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1318750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1595688],["domainDriver","Rebate Basis","select","Volume",["Volume","Growth","Product mix"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier agreement library case","Eligible product registry case","Purchase transaction ingestion case","Net purchase calculation case","Return exclusion control case"]}),
feature("eligible-product-registry","SRA02","Eligible product registry","Execute eligible product registry using supplier agreements, purchases, eligible products, tiers, growth targets, mix incentives, exclusions, accruals, claims, credits, and payments.","Produce a governed eligible product registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Rebate Program","text","Supplier / Rebate Program · Standard Case"],["caseReference","Eligible product registry Reference","text","SRA02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1318750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1595688],["domainDriver","Rebate Basis","select","Volume",["Volume","Growth","Product mix"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier agreement library case","Eligible product registry case","Purchase transaction ingestion case","Net purchase calculation case","Return exclusion control case"]}),
feature("purchase-transaction-ingestion","SRA03","Purchase transaction ingestion","Execute purchase transaction ingestion using supplier agreements, purchases, eligible products, tiers, growth targets, mix incentives, exclusions, accruals, claims, credits, and payments.","Produce a governed purchase transaction ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Rebate Program","text","Supplier / Rebate Program · Standard Case"],["caseReference","Purchase transaction ingestion Reference","text","SRA03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1318750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1595688],["domainDriver","Rebate Basis","select","Volume",["Volume","Growth","Product mix"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier agreement library case","Eligible product registry case","Purchase transaction ingestion case","Net purchase calculation case","Return exclusion control case"]}),
feature("net-purchase-calculation","SRA04","Net purchase calculation","Execute net purchase calculation using supplier agreements, purchases, eligible products, tiers, growth targets, mix incentives, exclusions, accruals, claims, credits, and payments.","Produce a governed net purchase calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Rebate Program","text","Supplier / Rebate Program · Standard Case"],["caseReference","Net purchase calculation Reference","text","SRA04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1318750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1595688],["domainDriver","Rebate Basis","select","Volume",["Volume","Growth","Product mix"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier agreement library case","Eligible product registry case","Purchase transaction ingestion case","Net purchase calculation case","Return exclusion control case"]}),
feature("return-exclusion-control","SRA05","Return exclusion control","Execute return exclusion control using supplier agreements, purchases, eligible products, tiers, growth targets, mix incentives, exclusions, accruals, claims, credits, and payments.","Produce a governed return exclusion control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Rebate Program","text","Supplier / Rebate Program · Standard Case"],["caseReference","Return exclusion control Reference","text","SRA05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1318750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1595688],["domainDriver","Rebate Basis","select","Volume",["Volume","Growth","Product mix"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier agreement library case","Eligible product registry case","Purchase transaction ingestion case","Net purchase calculation case","Return exclusion control case"]}),
feature("volume-tier-calculation","SRA06","Volume tier calculation","Execute volume tier calculation using supplier agreements, purchases, eligible products, tiers, growth targets, mix incentives, exclusions, accruals, claims, credits, and payments.","Produce a governed volume tier calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Rebate Program","text","Supplier / Rebate Program · Standard Case"],["caseReference","Volume tier calculation Reference","text","SRA06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1318750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1595688],["domainDriver","Rebate Basis","select","Volume",["Volume","Growth","Product mix"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier agreement library case","Eligible product registry case","Purchase transaction ingestion case","Net purchase calculation case","Return exclusion control case"]}),
feature("growth-baseline-calculation","SRA07","Growth baseline calculation","Execute growth baseline calculation using supplier agreements, purchases, eligible products, tiers, growth targets, mix incentives, exclusions, accruals, claims, credits, and payments.","Produce a governed growth baseline calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Rebate Program","text","Supplier / Rebate Program · Standard Case"],["caseReference","Growth baseline calculation Reference","text","SRA07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1318750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1595688],["domainDriver","Rebate Basis","select","Volume",["Volume","Growth","Product mix"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier agreement library case","Eligible product registry case","Purchase transaction ingestion case","Net purchase calculation case","Return exclusion control case"]}),
feature("product-mix-incentive","SRA08","Product mix incentive","Execute product mix incentive using supplier agreements, purchases, eligible products, tiers, growth targets, mix incentives, exclusions, accruals, claims, credits, and payments.","Produce a governed product mix incentive decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Rebate Program","text","Supplier / Rebate Program · Standard Case"],["caseReference","Product mix incentive Reference","text","SRA08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1318750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1595688],["domainDriver","Rebate Basis","select","Volume",["Volume","Growth","Product mix"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier agreement library case","Eligible product registry case","Purchase transaction ingestion case","Net purchase calculation case","Return exclusion control case"]}),
feature("customer-project-exclusion","SRA09","Customer project exclusion","Execute customer project exclusion using supplier agreements, purchases, eligible products, tiers, growth targets, mix incentives, exclusions, accruals, claims, credits, and payments.","Produce a governed customer project exclusion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Rebate Program","text","Supplier / Rebate Program · Standard Case"],["caseReference","Customer project exclusion Reference","text","SRA09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1318750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1595688],["domainDriver","Rebate Basis","select","Volume",["Volume","Growth","Product mix"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier agreement library case","Eligible product registry case","Purchase transaction ingestion case","Net purchase calculation case","Return exclusion control case"]}),
feature("rebate-accrual-ledger","SRA10","Rebate accrual ledger","Execute rebate accrual ledger using supplier agreements, purchases, eligible products, tiers, growth targets, mix incentives, exclusions, accruals, claims, credits, and payments.","Produce a governed rebate accrual ledger decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Rebate Program","text","Supplier / Rebate Program · Standard Case"],["caseReference","Rebate accrual ledger Reference","text","SRA10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1318750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1595688],["domainDriver","Rebate Basis","select","Volume",["Volume","Growth","Product mix"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier agreement library case","Eligible product registry case","Purchase transaction ingestion case","Net purchase calculation case","Return exclusion control case"]}),
feature("claim-preparation","SRA11","Claim preparation","Execute claim preparation using supplier agreements, purchases, eligible products, tiers, growth targets, mix incentives, exclusions, accruals, claims, credits, and payments.","Produce a governed claim preparation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Rebate Program","text","Supplier / Rebate Program · Standard Case"],["caseReference","Claim preparation Reference","text","SRA11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1318750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1595688],["domainDriver","Rebate Basis","select","Volume",["Volume","Growth","Product mix"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier agreement library case","Eligible product registry case","Purchase transaction ingestion case","Net purchase calculation case","Return exclusion control case"]}),
feature("supplier-statement-audit","SRA12","Supplier statement audit","Execute supplier statement audit using supplier agreements, purchases, eligible products, tiers, growth targets, mix incentives, exclusions, accruals, claims, credits, and payments.","Produce a governed supplier statement audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Rebate Program","text","Supplier / Rebate Program · Standard Case"],["caseReference","Supplier statement audit Reference","text","SRA12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1318750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1595688],["domainDriver","Rebate Basis","select","Volume",["Volume","Growth","Product mix"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier agreement library case","Eligible product registry case","Purchase transaction ingestion case","Net purchase calculation case","Return exclusion control case"]}),
feature("dispute-workflow","SRA13","Dispute workflow","Execute dispute workflow using supplier agreements, purchases, eligible products, tiers, growth targets, mix incentives, exclusions, accruals, claims, credits, and payments.","Produce a governed dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Rebate Program","text","Supplier / Rebate Program · Standard Case"],["caseReference","Dispute workflow Reference","text","SRA13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1318750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1595688],["domainDriver","Rebate Basis","select","Volume",["Volume","Growth","Product mix"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier agreement library case","Eligible product registry case","Purchase transaction ingestion case","Net purchase calculation case","Return exclusion control case"]}),
feature("credit-cash-reconciliation","SRA14","Credit cash reconciliation","Execute credit cash reconciliation using supplier agreements, purchases, eligible products, tiers, growth targets, mix incentives, exclusions, accruals, claims, credits, and payments.","Produce a governed credit cash reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Rebate Program","text","Supplier / Rebate Program · Standard Case"],["caseReference","Credit cash reconciliation Reference","text","SRA14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1318750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1595688],["domainDriver","Rebate Basis","select","Volume",["Volume","Growth","Product mix"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier agreement library case","Eligible product registry case","Purchase transaction ingestion case","Net purchase calculation case","Return exclusion control case"]}),
feature("program-supplier-analytics","SRA15","Program supplier analytics","Execute program supplier analytics using supplier agreements, purchases, eligible products, tiers, growth targets, mix incentives, exclusions, accruals, claims, credits, and payments.","Produce a governed program supplier analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Rebate Program","text","Supplier / Rebate Program · Standard Case"],["caseReference","Program supplier analytics Reference","text","SRA15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1318750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1595688],["domainDriver","Rebate Basis","select","Volume",["Volume","Growth","Product mix"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier agreement library case","Eligible product registry case","Purchase transaction ingestion case","Net purchase calculation case","Return exclusion control case"]})
]);
